spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/securityproject?useUnicode=true&characterEncoding=utf-8
    username: myadmin
    password: mariadb

  security:
    user:
      name: user
      password: 1111

  jpa:
    hibernate:
      ddl-auto: update #update create none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  main:
    allow-bean-definition-overriding: true